# Generated by Django 3.1.2 on 2020-10-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='type_pet',
            new_name='type',
        ),
    ]
